Juan Fernando Salgado Lozano

c.c 1006461909

A) 1.

In [ ]:
import numpy as np
#Usando su número de cédula cómo semilla, obtenga un numero entero aleatorio, n, entre 2 y 20.
np.random.seed(1006461909)
n= np.random.randint(2, 20)
n

2

2.

In [ ]:
from sympy import sin,integrate
from sympy.abc import x

f = integrate(sin(x**n), (x, 0, sp.oo))
f

sqrt(2)*sqrt(pi)/4

In [ ]:
import numpy as np
import sympy as sp
import scipy
from scipy.integrate import quad
#Usando el n obtenido, haga una estimación de la siguiente integral hasta dos cifras significativas, usando el método quad del módulo integrate de Scipy
Linf = 0
Lsup = sp.oo

def k(x):
  return (np.sqrt(2)*np.sqrt(np.pi))/4

valor,error = quad(k, Linf, Lsup)
print ("Integral value of sin(x**n) from 0 to infinite is:", valor)
print ("Estimated error is: ", error)

Integral value of sin(x**n) from 0 to infinite is: -0.6266570686581293
Estimated error is:  1.7151835507434043e-12


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  if sys.path[0] == '':


B) 1.

In [ ]:
import requests, json

response = requests.get("https://raw.githubusercontent.com/ComputationalMethods/Evaluacion_2022-1/main/data/lista_pares.json")
rawjson = response.json()
df = pd.DataFrame(rawjson)
df

lista  \
0          [1, 1, 2, 3, -4, -4, -5, 6]   
1          [1, 2, 2, 2, -3, -5, -6, 7]   
2         [1, -2, -2, 4, 5, -7, -7, 8]   
3          [1, 2, 2, 4, -5, -5, -7, 8]   
4         [2, -3, -4, 5, -6, 7, 7, -8]   
..                                 ...   
240  [2, -4, -5, 10, 11, -16, -17, 19]   
241  [5, -7, -7, 11, 13, -17, -17, 19]   
242   [4, -5, -7, 8, -17, 18, 18, -19]   
243    [2, 2, 5, -7, 10, -14, -17, 19]   
244   [2, -3, -3, 6, 10, -13, -18, 19]   

                                                 pares  
0    {'S': 2, 'ψ': [[3, -5], [2, -4], [-4, 6], [1, ...  
1    {'S': 4, 'ψ': [[2, 2], [-3, 7], [1, -5], [2, -...  
2    {'S': 9, 'ψ': [[4, 5], [1, 8], [-2, -7], [5, 4...  
3    {'S': 3, 'ψ': [[4, -7], [-5, 8], [2, -5], [1, ...  
4    {'S': 1, 'ψ': [[-6, 7], [7, -8], [5, -6], [2, ...  
..                                                 ...  
240  {'S': 21, 'ψ': [[-4, -17], [-5, -16], [10, 11]...  
241  {'S': 24, 'ψ': [[5, 19], [-7, -17], [11, 13], ...  
242  {'S': 1, 'ψ': [[-7, 8], [4, -5], [-17, 18], [1...  
243  {'S': 12, 'ψ': [[2, -14], [2, 10], [-7, 19], [...  
244  {'S': 16, 'ψ': [[-3, -13], [6, 10], [2, -18], ...  

[245 rows x 2 columns]

In [ ]:
#índice correspondiente a los dos últimos dígitos la cédula (09)
dt = df.iloc[9]
dt

lista                         [3, -4, -6, -6, 7, 7, 8, -9]
pares    {'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9,...
Name: 9, dtype: object

In [ ]:
import pandas as pd

dt = df.iloc[9]
pd.DataFrame(dt)

9
lista                       [3, -4, -6, -6, 7, 7, 8, -9]
pares  {'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9,...

In [ ]:
dt['lista']


[3, -4, -6, -6, 7, 7, 8, -9]

In [ ]:
dt['pares']

{'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9, 8], [7, -6], [-4, 3]]}

In [235]:
import numpy as np
import random

M = np.zeros([8,8])

for fila, i in enumerate(dt.lista):
  for columna, j in enumerate(dt.lista):
    if [i,j] in dt.pares['ψ']:
      M[fila,columna] = round(random.random(),3)

M

array([[0.   , 0.588, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.577, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.943, 0.494, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.469, 0.921, 0.   , 0.   ],
       [0.   , 0.   , 0.38 , 0.383, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.666, 0.129, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.012],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.749, 0.   ]])

2.

In [236]:
det = np.linalg.det(M)
print(det)
det != 0

-0.00040014770621992786


True

3.

In [237]:
valores,vectores = np.linalg.eig(M)

In [238]:
valores

array([ 5.82474034e-01+0.j        , -5.82474034e-01+0.j        ,
        1.05098889e+00+0.j        , -1.05098889e+00+0.j        ,
        3.94430453e-31+0.34467036j,  3.94430453e-31-0.34467036j,
        9.48050632e-02+0.j        , -9.48050632e-02+0.j        ])

In [239]:
ab = abs(valores)
ab

array([0.58247403, 0.58247403, 1.05098889, 1.05098889, 0.34467036,
       0.34467036, 0.09480506, 0.09480506])

In [240]:
Aab = sorted(ab) #Autovalores ordenados + valor absoluto
Aab

[0.09480506315593065,
 0.09480506315593065,
 0.3446703596245245,
 0.3446703596245245,
 0.582474033756012,
 0.5824740337560121,
 1.0509888947099768,
 1.0509888947099768]

In [241]:
vectores

array([[ 7.10437210e-01+0.00000000e+00j, -7.10437210e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 7.03760591e-01+0.00000000e+00j,  7.03760591e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        -5.72536370e-01+0.00000000e+00j,  5.72536370e-01+0.00000000e+00j,
        -3.75162882e-01-4.89106970e-17j, -3.75162882e-01+4.89106970e-17j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
        -5.62212884e-01+0.00000000e

In [243]:
bc = abs(vectores)
bc

array([[0.71043721, 0.71043721, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.70376059, 0.70376059, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.57253637, 0.57253637, 0.37516288,
        0.37516288, 0.        , 0.        ],
       [0.        , 0.        , 0.56221288, 0.56221288, 0.71178627,
        0.71178627, 0.        , 0.        ],
       [0.        , 0.        , 0.41188956, 0.41188956, 0.37732356,
        0.37732356, 0.        , 0.        ],
       [0.        , 0.        , 0.43181682, 0.43181682, 0.45851941,
        0.45851941, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.12557359, 0.12557359],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.99208431, 0.99208431]])

4.

In [245]:
print(ab)
print(Aab)

[0.58247403 0.58247403 1.05098889 1.05098889 0.34467036 0.34467036
 0.09480506 0.09480506]
[0.09480506315593065, 0.09480506315593065, 0.3446703596245245, 0.3446703596245245, 0.582474033756012, 0.5824740337560121, 1.0509888947099768, 1.0509888947099768]
