Juan Fernando Salgado Lozano

c.c 1006461909

A) 1.

In [ ]:
import numpy as np
#Usando su número de cédula cómo semilla, obtenga un numero entero aleatorio, n, entre 2 y 20.
np.random.seed(1006461909)
n= np.random.randint(2, 20)
n

2

2.

In [ ]:
from sympy import sin,integrate
from sympy.abc import x

f = integrate(sin(x**n), (x, 0, sp.oo))
f

sqrt(2)*sqrt(pi)/4

In [ ]:
import numpy as np
import sympy as sp
import scipy
from scipy.integrate import quad
#Usando el n obtenido, haga una estimación de la siguiente integral hasta dos cifras significativas, usando el método quad del módulo integrate de Scipy
Linf = 0
Lsup = sp.oo

def k(x):
  return (np.sqrt(2)*np.sqrt(np.pi))/4

valor,error = quad(k, Linf, Lsup)
print ("Integral value of sin(x**n) from 0 to infinite is:", valor)
print ("Estimated error is: ", error)

Integral value of sin(x**n) from 0 to infinite is: -0.6266570686581293
Estimated error is:  1.7151835507434043e-12


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  if sys.path[0] == '':


B) 1.

In [ ]:
import requests, json

response = requests.get("https://raw.githubusercontent.com/ComputationalMethods/Evaluacion_2022-1/main/data/lista_pares.json")
rawjson = response.json()
df = pd.DataFrame(rawjson)
df

lista  \
0          [1, 1, 2, 3, -4, -4, -5, 6]   
1          [1, 2, 2, 2, -3, -5, -6, 7]   
2         [1, -2, -2, 4, 5, -7, -7, 8]   
3          [1, 2, 2, 4, -5, -5, -7, 8]   
4         [2, -3, -4, 5, -6, 7, 7, -8]   
..                                 ...   
240  [2, -4, -5, 10, 11, -16, -17, 19]   
241  [5, -7, -7, 11, 13, -17, -17, 19]   
242   [4, -5, -7, 8, -17, 18, 18, -19]   
243    [2, 2, 5, -7, 10, -14, -17, 19]   
244   [2, -3, -3, 6, 10, -13, -18, 19]   

                                                 pares  
0    {'S': 2, 'ψ': [[3, -5], [2, -4], [-4, 6], [1, ...  
1    {'S': 4, 'ψ': [[2, 2], [-3, 7], [1, -5], [2, -...  
2    {'S': 9, 'ψ': [[4, 5], [1, 8], [-2, -7], [5, 4...  
3    {'S': 3, 'ψ': [[4, -7], [-5, 8], [2, -5], [1, ...  
4    {'S': 1, 'ψ': [[-6, 7], [7, -8], [5, -6], [2, ...  
..                                                 ...  
240  {'S': 21, 'ψ': [[-4, -17], [-5, -16], [10, 11]...  
241  {'S': 24, 'ψ': [[5, 19], [-7, -17], [11, 13], ...  
242  {'S': 1, 'ψ': [[-7, 8], [4, -5], [-17, 18], [1...  
243  {'S': 12, 'ψ': [[2, -14], [2, 10], [-7, 19], [...  
244  {'S': 16, 'ψ': [[-3, -13], [6, 10], [2, -18], ...  

[245 rows x 2 columns]

In [ ]:
#índice correspondiente a los dos últimos dígitos la cédula (09)
dt = df.iloc[9]
dt

lista                         [3, -4, -6, -6, 7, 7, 8, -9]
pares    {'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9,...
Name: 9, dtype: object

In [ ]:
import pandas as pd

dt = df.iloc[9]
pd.DataFrame(dt)

9
lista                       [3, -4, -6, -6, 7, 7, 8, -9]
pares  {'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9,...

In [ ]:
dt['lista']


[3, -4, -6, -6, 7, 7, 8, -9]

In [ ]:
dt['pares']

{'S': 1, 'ψ': [[8, -9], [-6, 7], [3, -4], [-9, 8], [7, -6], [-4, 3]]}

In [ ]:
import numpy as np
M = np.zeros((8,8))
M

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
import random
a1 = random.uniform(0,1)
a2 = random.uniform(0,1)
a3 = random.uniform(0,1)
a4 = random.uniform(0,1)
a5 = random.uniform(0,1)
a6 = random.uniform(0,1)
a7 = random.uniform(0,1)
a8 = random.uniform(0,1)
a9 = random.uniform(0,1)
a10 = random.uniform(0,1)
a11 = random.uniform(0,1)
a12 = random.uniform(0,1)

In [ ]:
M[1,0] = a1
M[0,1] = a2
M[4,2] = a3
M[5,2] = a4
M[4,3] = a5
M[5,3] = a6
M[2,4] = a7
M[3,4] = a8
M[2,5] = a9
M[3,5] = a10
M[7,6] = a11
M[6,7] = a12
print(M)

[[0.         0.86024556 0.         0.         0.         0.
  0.         0.        ]
 [0.2425512  0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.1399048  0.77249427
  0.         0.        ]
 [0.         0.         0.         0.         0.14030955 0.25751039
  0.         0.        ]
 [0.         0.         0.96940538 0.00811587 0.         0.
  0.         0.        ]
 [0.         0.         0.44124689 0.28278938 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.35522426]
 [0.         0.         0.         0.         0.         0.
  0.71644095 0.        ]]


In [ ]:
M

array([[0.        , 0.86024556, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.2425512 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.1399048 ,
        0.77249427, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.14030955,
        0.25751039, 0.        , 0.        ],
       [0.        , 0.        , 0.96940538, 0.00811587, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.44124689, 0.28278938, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.35522426],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.71644095, 0.        ]])

2.

In [ ]:
det = np.linalg.det(M)
print(det)
det != 0

-0.0010396176643937185


True

3.

In [ ]:
valores,vectores = np.linalg.eig(M)

In [ ]:
valores

array([-7.64179616e-01+0.j       , -5.04477160e-01+0.j       ,
       -4.56786159e-01+0.j       , -3.46944695e-17-0.1830994j,
       -3.46944695e-17+0.1830994j,  4.56786159e-01+0.j       ,
        5.04477160e-01+0.j       ,  7.64179616e-01+0.j       ])

In [ ]:
ab = abs(valores)
ab

array([0.76417962, 0.50447716, 0.45678616, 0.1830994 , 0.1830994 ,
       0.45678616, 0.50447716, 0.76417962])

In [ ]:
Aab = sorted(ab) #Autovalores ordenados + valor absoluto
Aab

[0.1830994040835894,
 0.1830994040835894,
 0.45678615937395123,
 0.45678615937395134,
 0.5044771601517491,
 0.5044771601517491,
 0.764179616473589,
 0.7641796164735892]

In [ ]:
vectores

array([[ 8.83208985e-01+0.00000000e+00j, -8.83208985e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 4.68979624e-01+0.00000000e+00j,  4.68979624e-01+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00-0.00000000e+00j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         5.39364138e-01+0.00000000e+00j,  5.39364138e-01+0.00000000e+00j,
        -9.95684317e-17+1.69682630e-01j, -9.95684317e-17-1.69682630e-01j,
         0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j],
       [ 0.00000000e+00+0.00000000e+00j,  0.00000000e+00+0.00000000e+00j,
         2.64010638e-01+0.00000000e

In [ ]:
bc = abs(vectores)
bc

array([[0.88320899, 0.88320899, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.46897962, 0.46897962, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.53936414, 0.53936414, 0.16968263,
        0.16968263, 0.        , 0.        ],
       [0.        , 0.        , 0.26401064, 0.26401064, 0.39410025,
        0.39410025, 0.        , 0.        ],
       [0.        , 0.        , 0.68701803, 0.68701803, 0.88090286,
        0.88090286, 0.        , 0.        ],
       [0.        , 0.        , 0.40913438, 0.40913438, 0.19975724,
        0.19975724, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57573382, 0.57573382],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.81763719, 0.81763719]])